print("Введите значение x1")
x1 = int(input())
print("Введите значение x2")
x2 = int(input())
print("Введите значение y1")
y1 = int(input())
print("Введите значение y2")
y2 = int(input())
print("Расстояние между двумя точками равно:")
print(((x2-x1) + (y2-y1)**0.5))